spring:
  datasource:
    url: jdbc:h2:mem:book-library
  h2:
    console:
      path: /h2-console
      enabled: true
  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false