DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USER_ROLE;

CREATE TABLE AUTHORS(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE GENRES(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE BOOKS(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR_ID INTEGER NOT NULL,
    GENRE_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID)
);

CREATE TABLE COMMENTS(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ENTRY VARCHAR(255) NOT NULL,
    BOOK_ID INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE CASCADE
);

CREATE TABLE USERS(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLE(
    USER_ID BIGINT not null,
    ROLES VARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

/*------------ ACL ------------*/
DROP TABLE IF EXISTS acl_sid;
DROP TABLE IF EXISTS acl_class;
DROP TABLE IF EXISTS acl_entry;
DROP TABLE IF EXISTS acl_object_identity;

CREATE TABLE acl_sid(
    id bigint NOT NULL AUTO_INCREMENT,
    principal tinyint NOT NULL,
    sid varchar(100) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_uk_1 UNIQUE (sid,principal)
);

CREATE TABLE acl_class (
    id bigint NOT NULL AUTO_INCREMENT,
    class varchar(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_uk_2 UNIQUE (class)
);

CREATE TABLE acl_entry (
    id bigint NOT NULL AUTO_INCREMENT,
    acl_object_identity bigint NOT NULL,
    ace_order int NOT NULL,
    sid bigint NOT NULL,
    mask int NOT NULL,
    granting tinyint NOT NULL,
    audit_success tinyint NOT NULL,
    audit_failure tinyint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_uk_4 UNIQUE (acl_object_identity,ace_order)
);

CREATE TABLE acl_object_identity (
    id bigint NOT NULL AUTO_INCREMENT,
    object_id_class bigint NOT NULL,
    object_id_identity bigint NOT NULL,
    parent_object bigint DEFAULT NULL,
    owner_sid bigint DEFAULT NULL,
    entries_inheriting tinyint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_uk_3 UNIQUE (object_id_class,object_id_identity)
);

ALTER TABLE acl_entry
    ADD FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity(id);

ALTER TABLE acl_entry
    ADD FOREIGN KEY (sid) REFERENCES acl_sid(id);

--
-- Constraints for table acl_object_identity
--
ALTER TABLE acl_object_identity
    ADD FOREIGN KEY (parent_object) REFERENCES acl_object_identity (id);

ALTER TABLE acl_object_identity
    ADD FOREIGN KEY (object_id_class) REFERENCES acl_class (id);

ALTER TABLE acl_object_identity
    ADD FOREIGN KEY (owner_sid) REFERENCES acl_sid (id);