spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:book-library
  h2:
    console:
      path: /h2-console
      enabled: true
  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true

logging:
  file:
    path: ./log
  logback:
    rollingpolicy:
      clean-history-on-start: true